baseURL = "https://alx.github.io/flight_strait/"
languageCode = "en-us"
title = "Trabzon Overflight Tracker"
ignoreFiles = ['data/raw/.*\.jsonl$']

[params]
  trabzonLat = 40.995
  trabzonLon = 39.789
  queryLat = 40.995
  queryLon = 39.789
  queryRadiusNm = 150
